# Sample configuration file for metagenomic analysis
# Farting Trees Project

# Data paths
DATA_DIR: "../data"
RESULTS_DIR: "../results"

# Computing resources
THREADS: 8
MEMORY_GB: 32

# Quality control parameters
QC:
  min_quality: 20
  min_length: 50
  adapter_removal: true

# Assembly parameters
ASSEMBLY:
  min_contig_length: 1000
  assemblers: ["megahit", "spades"]
  
# Binning parameters
BINNING:
  min_contig_length: 2500
  binners: ["metabat2", "maxbin2", "vamb"]
  use_das_tool: true

# Quality thresholds for MAGs
MAG_QUALITY:
  high_quality:
    completeness: 90
    contamination: 5
  medium_quality:
    completeness: 50
    contamination: 10

# Target organisms
TARGETS:
  methanogens:
    - "Methanobrevibacter"
    - "Methanococcus" 
    - "Methanosarcina"
    - "Methanothermobacter"
  methanotrophs:
    - "Methylococcus"
    - "Methylosinus"
    - "Methylocystis"
    - "Methylobacter"

# Functional genes of interest
FUNCTIONAL_GENES:
  methanogenesis:
    - "mcrA"  # methyl-coenzyme M reductase alpha subunit
    - "mcrB"  # methyl-coenzyme M reductase beta subunit  
    - "mcrG"  # methyl-coenzyme M reductase gamma subunit
    - "fmdA"  # formylmethanofuran dehydrogenase
  methanotrophy:
    - "mmoX"  # methane monooxygenase alpha subunit
    - "pmoA"  # particulate methane monooxygenase alpha subunit
    - "mxaF"  # methanol dehydrogenase alpha subunit
